Add Redis complete configuration

diff --git a/jumpserver/jumpserver/Dockerfile b/jumpserver/jumpserver/Dockerfile
--- a/jumpserver/jumpserver/Dockerfile
+++ b/jumpserver/jumpserver/Dockerfile
@@ -1,12 +1,49 @@
 FROM alpine:3.9
 
-ARG JUMPSERVER_VERSION=1.5.2
+ARG ALPINE_VERSION=3.9
+
+RUN set -ex && \
+    echo "" > /etc/apk/repositories && \
+    if [ "${ALPINE_VERSION}" != "edge" ]; then ALPINE_VERSION=v`cat /etc/alpine-release | awk -F '.' '{print $1"."$2}'`; fi && \
+    echo "https://mirrors.aliyun.com/alpine/${ALPINE_VERSION}/main" >> /etc/apk/repositories && \
+    echo "https://mirrors.aliyun.com/alpine/${ALPINE_VERSION}/community" >> /etc/apk/repositories && \
+    if [ "${ALPINE_VERSION}" = "edge" ]; then echo "https://mirrors.aliyun.com/alpine/${ALPINE_VERSION}/testing" >> /etc/apk/repositories; fi && \
+    echo "https://mirrors.ustc.edu.cn/alpine/${ALPINE_VERSION}/main" >> /etc/apk/repositories && \
+    echo "https://mirrors.ustc.edu.cn/alpine/${ALPINE_VERSION}/community" >> /etc/apk/repositories && \
+    if [ "${ALPINE_VERSION}" = "edge" ]; then echo "https://mirrors.ustc.edu.cn/alpine/${ALPINE_VERSION}/testing" >> /etc/apk/repositories; fi && \
+    echo "http://dl-cdn.alpinelinux.org/alpine/${ALPINE_VERSION}/main" >> /etc/apk/repositories && \
+    echo "http://dl-cdn.alpinelinux.org/alpine/${ALPINE_VERSION}/community" >> /etc/apk/repositories && \
+    if [ "${ALPINE_VERSION}" = "edge" ]; then echo "http://dl-cdn.alpinelinux.org/alpine/${ALPINE_VERSION}/testing" >> /etc/apk/repositories; fi && \
+    apk upgrade
+
+# 配置系统语言环境
+RUN set -x && \
+    GLIBC_VERSION=2.30-r0 && \
+    wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub || \
+        echo "Download error return $?" && \
+    wget -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk || \
+        echo "Download error return $?" && \
+    wget -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}.apk || \
+        echo "Download error return $?" && \
+    wget -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-i18n-${GLIBC_VERSION}.apk || \
+        echo "Download error return $?" && \
+    if [ ! -f /etc/apk/keys/sgerrand.rsa.pub ]; then wget -q http://file.openeasy.cn/alpine/sgerrand.rsa.pub -O /etc/apk/keys/sgerrand.rsa.pub || exit 1; fi && \
+    if [ ! -f glibc-${GLIBC_VERSION}.apk ]; then wget -q http://file.openeasy.cn/alpine/glibc/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk || exit 1; fi && \
+    if [ ! -f glibc-bin-${GLIBC_VERSION}.apk ]; then wget -q http://file.openeasy.cn/alpine/glibc/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}.apk || exit 1; fi && \
+    if [ ! -f glibc-i18n-${GLIBC_VERSION}.apk ]; then wget -q http://file.openeasy.cn/alpine/glibc/${GLIBC_VERSION}/glibc-i18n-${GLIBC_VERSION}.apk || exit 1; fi && \
+    apk add glibc-bin-${GLIBC_VERSION}.apk glibc-i18n-${GLIBC_VERSION}.apk glibc-${GLIBC_VERSION}.apk && \
+    rm -rf glibc-bin-${GLIBC_VERSION}.apk glibc-i18n-${GLIBC_VERSION}.apk glibc-${GLIBC_VERSION}.apk && \
+    rm -rf /var/cache/apk/*
+RUN printf "zh_CN\nzh_HK\nzh_TW" | xargs -i /usr/glibc-compat/bin/localedef -c -f UTF-8 -i {} {}.UTF-8
+ENV LC_ALL=zh_CN.UTF-8
+ENV LANG=zh_CN.UTF-8
+
 ARG ZONE_NAME="Asia/Shanghai"
 ARG USER=jumpserver
 ARG GROUP=jumpserver
+ARG HOME=/usr/jumpserver
 
 RUN set -ex && \
-    echo http://dl-cdn.alpinelinux.org/alpine/edge/testing/ >> /etc/apk/repositories && \
     apk upgrade && \
     apk add shadow tzdata && \
     # 初始化时区
@@ -15,88 +52,35 @@ RUN set -ex && \
     cat /etc/group | grep :999: | awk -F ':' '{print "groupmod -g 1999 "$1}' | sh && \
     cat /etc/passwd | grep :999: | awk -F ':' '{print "usermod -u 1999 "$1}' | sh && \
     cat /etc/group | grep ${GROUP}: | awk -F ':' '{print "groupmod -g 999 "$1}' | sh && \
-    cat /etc/passwd | grep ${USER}: | awk -F ':' '{print "usermod -u 999 "$1}' | sh && \
+    cat /etc/passwd | grep ${USER}: | awk -F ':' '{print "usermod -u 999 -m -d ${HOME} "$1}' | sh && \
     cat /etc/group | grep ${GROUP}: || sh -c "groupadd -r -g 999 ${GROUP}" && \
-    cat /etc/passwd | grep ${USER}: || sh -c "useradd -r -u 999 -g ${GROUP} ${USER} -m -d /home/${USER} -s /bin/sh" && \
-    HOME=$(cat /etc/passwd | grep www | awk -F ':' '{print $6}') && \
-    if [ ! -d ${HOME} ]; then mkdir -p ${HOME}; fi && \
+    cat /etc/passwd | grep ${USER}: || sh -c "useradd -r -u 999 -g ${GROUP} ${USER} -m -d ${HOME} -s /bin/sh" && \
+    HOME=$(cat /etc/passwd | grep ${USER} | awk -F ':' '{print $6}') && \
+    if [ ! -d ${HOME} ]; then mkdir -p ${HOME}; chown ${USER}:${GROUP} ${HOME}; fi && \
     apk del shadow && \
     rm -rf /var/cache/apk/*
 
-# # 配置系统语言环境
-# RUN set -ex && \
-#     GLIBC_VERSION=2.30-r0 && \
-#     wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub && \
-#     wget -q http://file.openeasy.cn/alpine/glibc/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk && \
-#     wget -q http://file.openeasy.cn/alpine/glibc/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}.apk && \
-#     wget -q http://file.openeasy.cn/alpine/glibc/${GLIBC_VERSION}/glibc-i18n-${GLIBC_VERSION}.apk && \
-#     apk add glibc-bin-${GLIBC_VERSION}.apk glibc-i18n-${GLIBC_VERSION}.apk glibc-${GLIBC_VERSION}.apk && \
-#     rm -rf glibc-bin-${GLIBC_VERSION}.apk glibc-i18n-${GLIBC_VERSION}.apk glibc-${GLIBC_VERSION}.apk && \
-#     rm -rf /var/cache/apk/*
-# RUN printf "zh_CN\nzh_HK\nzh_TW" | xargs -i /usr/glibc-compat/bin/localedef -c -f UTF-8 -i {} {}.UTF-8
-# ENV LC_ALL=zh_CN.UTF-8
-# ENV LANG=zh_CN.UTF-8
-
-RUN set -x && \
-    GLIBC_VERSION=2.30-r0 && \
-    wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub && \
-    wget -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk && \
-    wget -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}.apk && \
-    wget -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-i18n-${GLIBC_VERSION}.apk && \
-    if [ ! -f /etc/apk/keys/sgerrand.rsa.pub ]; then wget -q -O /etc/apk/keys/sgerrand.rsa.pub http://file.openeasy.cn/alpine/sgerrand.rsa.pub || exit 1; fi && \
-    if [ ! -f glibc-${GLIBC_VERSION}.apk ]; then wget -q http://file.openeasy.cn/alpine/glibc/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk || exit 1; fi && \
-    if [ ! -f glibc-bin-${GLIBC_VERSION}.apk ]; then wget -q http://file.openeasy.cn/alpine/glibc/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}.apk || exit 1; fi && \
-    if [ ! -f glibc-i18n-${GLIBC_VERSION}.apk ]; then wget -q http://file.openeasy.cn/alpine/glibc/${GLIBC_VERSION}/glibc-i18n-${GLIBC_VERSION}.apk || exit 1; fi && \
-    apk add glibc-bin-${GLIBC_VERSION}.apk glibc-i18n-${GLIBC_VERSION}.apk glibc-${GLIBC_VERSION}.apk && \
-    printf "zh_CN\nzh_HK\nzh_TW" | xargs -i /usr/glibc-compat/bin/localedef -c -f UTF-8 -i {} {}.UTF-8 && \
-    apk del glibc-bin glibc-i18n glibc && rm -rf /etc/apk/keys/sgerrand.rsa.pub && \
-    rm -rf glibc-bin-${GLIBC_VERSION}.apk glibc-i18n-${GLIBC_VERSION}.apk glibc-${GLIBC_VERSION}.apk && \
-    rm -rf /var/cache/apk/* && echo 1 && exit 1
-
-
-# # echo http://dl-2.alpinelinux.org/alpine/edge/main/ >> /etc/apk/repositories && \
-# # echo http://dl-2.alpinelinux.org/alpine/edge/community/ >> /etc/apk/repositories && \
-# RUN set -ex && \
-#     apk --no-cache add ca-certificates wget shadow && \
-#     rm -rf /var/cache/apk/*
-
-# # 配置系统语言环境
-# RUN set -ex && \
-#     GLIBC_VERSION=2.30-r0 && \
-#     wget -nv -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub && \
-#     wget -nv http://file.openeasy.cn/alpine/glibc/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk && \
-#     wget -nv http://file.openeasy.cn/alpine/glibc/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}.apk && \
-#     wget -nv http://file.openeasy.cn/alpine/glibc/${GLIBC_VERSION}/glibc-i18n-${GLIBC_VERSION}.apk && \
-#     apk add glibc-bin-${GLIBC_VERSION}.apk glibc-i18n-${GLIBC_VERSION}.apk glibc-${GLIBC_VERSION}.apk && \
-#     rm -rf glibc-bin-${GLIBC_VERSION}.apk glibc-i18n-${GLIBC_VERSION}.apk glibc-${GLIBC_VERSION}.apk
-
-# RUN printf "zh_CN" | xargs -i /usr/glibc-compat/bin/localedef -c -f UTF-8 -i {} {}.UTF-8
-# ENV LC_ALL=zh_CN.UTF-8
-# ENV LANG=zh_CN.UTF-8
-
-# RUN echo "Asia/Shanghai" > /etc/timezone && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
-
-# RUN cat /etc/group | grep :999: | awk -F ':' '{print "groupmod -g 1999 "$1}' | sh && \
-#     groupadd -r -g 999 jumpserver && \
-#     useradd -r -u 999 -g jumpserver jumpserver -m -d /home/jumpserver -s /bin/bash
-
-ARG JUMPSERVER_HOME=/usr/jumpserver
-
+ARG JUMPSERVER_VERSION=1.5.6
+ARG JUMPSERVER_HOME=${HOME}
 WORKDIR ${JUMPSERVER_HOME}
-
-ADD src/jumpserver-${JUMPSERVER_VERSION}.tar.gz ./
 
 # 安装依赖包
 RUN set -ex && \
-    mv ${JUMPSERVER_HOME}/jumpserver-${JUMPSERVER_VERSION}/* ${JUMPSERVER_HOME} && \
-    rm -rf ${JUMPSERVER_HOME}/jumpserver-${JUMPSERVER_VERSION} && \
-    sed -i "s/mysqlclient.*/postgres==2.2.2\\n&/g" ${JUMPSERVER_HOME}/requirements/requirements.txt && \
-    # apk --no-cache add bash && \
+    wget https://github.com/jumpserver/jumpserver/archive/${JUMPSERVER_VERSION}.tar.gz \
+        -O jumpserver-${JUMPSERVER_VERSION}.tar.gz && \
+    wget https://github.com/jumpserver/luna/releases/download/${JUMPSERVER_VERSION}/luna.tar.gz \
+        -O luna-${JUMPSERVER_VERSION}.tar.gz && \
+    tar xf jumpserver-${JUMPSERVER_VERSION}.tar.gz --strip-components=1 && \
+    tar xf luna-${JUMPSERVER_VERSION}.tar.gz && \
+    chown -R ${USER}:${GROUP} ${JUMPSERVER_HOME} && \
     apk --no-cache add $(cat ${JUMPSERVER_HOME}/requirements/alpine_requirements.txt) && \
-    rm -rf /var/cache/apk/* && \
-    pip3 install --upgrade pip setuptools -i https://mirrors.aliyun.com/pypi/simple/ && \
-    pip3 install -r  ${JUMPSERVER_HOME}/requirements/requirements.txt -i https://mirrors.aliyun.com/pypi/simple/ && \
-    rm -rf /root/.cache
+    rm -rf jumpserver-${JUMPSERVER_VERSION}.tar.gz luna-${JUMPSERVER_VERSION}.tar.gz /var/cache/apk/* /tmp/*
+
+RUN set -ex && \
+    pip3 install --upgrade pip setuptools wheel -i https://mirrors.aliyun.com/pypi/simple/ && \
+    sed -i "s/mysqlclient.*/postgres==2.2.2\\n&/g" ${JUMPSERVER_HOME}/requirements/requirements.txt && \
+    pip3 install -r ${JUMPSERVER_HOME}/requirements/requirements.txt -i https://mirrors.aliyun.com/pypi/simple/ && \
+    rm -rf /tmp/* ${JUMPSERVER_HOME}/.cache
 
 # postgresql/mysql
 ENV DB_ENGINE=postgresql
@@ -109,20 +93,22 @@ ENV DB_PASSWORD=Abc123
 ENV REDIS_HOST=172.17.0.1
 ENV REDIS_PORT=6379
 ENV REDIS_PASSWORD=
+ENV REDIS_DB_CELERY=
+ENV REDIS_DB_CACHE=
 
-ENV SECRET_KEY=ww2ZkPHHXbe5ydtpdkG0FoYrSjAnxRfx6RJAqlE959ThckZhHF
-ENV BOOTSTRAP_TOKEN=DdC9ASWbpzq6WACk
+ENV SECRET_KEY=
+ENV BOOTSTRAP_TOKEN=
 
 ENV DEBUG=false
 # DEBUG/ERROR
 ENV LOG_LEVEL=ERROR
 
 
-ADD startup.sh jumpserver.conf src/luna-${JUMPSERVER_VERSION}.tar.gz ./
+ADD startup.sh jumpserver.conf ./
 
 RUN chmod 755 startup.sh && \
     > .dockerenv
 
 EXPOSE 8080
 
-ENTRYPOINT ["./startup.sh"]
+CMD ["./startup.sh"]
