Add hll extensions and get all the latest extensions automatically

diff --git a/postgres/Dockerfile b/postgres/Dockerfile
--- a/postgres/Dockerfile
+++ b/postgres/Dockerfile
@@ -1,6 +1,28 @@
 FROM alpine:edge
 
-ARG POSTGRES_VERSION=11.5
+# 配置系统语言环境
+RUN set -x && \
+    GLIBC_VERSION=2.30-r0 && \
+    wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub || \
+        echo "Download error return $?" && \
+    wget -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk || \
+        echo "Download error return $?" && \
+    wget -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}.apk || \
+        echo "Download error return $?" && \
+    wget -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-i18n-${GLIBC_VERSION}.apk || \
+        echo "Download error return $?" && \
+    if [ ! -f /etc/apk/keys/sgerrand.rsa.pub ]; then wget -q http://file.openeasy.cn/alpine/sgerrand.rsa.pub \
+        -O /etc/apk/keys/sgerrand.rsa.pub || exit 1; fi && \
+    if [ ! -f glibc-${GLIBC_VERSION}.apk ]; then wget -q http://file.openeasy.cn/alpine/glibc/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk || exit 1; fi && \
+    if [ ! -f glibc-bin-${GLIBC_VERSION}.apk ]; then wget -q http://file.openeasy.cn/alpine/glibc/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}.apk || exit 1; fi && \
+    if [ ! -f glibc-i18n-${GLIBC_VERSION}.apk ]; then wget -q http://file.openeasy.cn/alpine/glibc/${GLIBC_VERSION}/glibc-i18n-${GLIBC_VERSION}.apk || exit 1; fi && \
+    apk add glibc-bin-${GLIBC_VERSION}.apk glibc-i18n-${GLIBC_VERSION}.apk glibc-${GLIBC_VERSION}.apk && \
+    rm -rf glibc-bin-${GLIBC_VERSION}.apk glibc-i18n-${GLIBC_VERSION}.apk glibc-${GLIBC_VERSION}.apk && \
+    rm -rf /var/cache/apk/*
+RUN printf "zh_CN\nzh_HK\nzh_TW" | xargs -i /usr/glibc-compat/bin/localedef -c -f UTF-8 -i {} {}.UTF-8
+ENV LC_ALL=zh_CN.UTF-8
+ENV LANG=zh_CN.UTF-8
+
 ARG ZONE_NAME="Asia/Shanghai"
 ARG USER=postgres
 ARG GROUP=postgres
@@ -23,24 +45,6 @@ RUN set -ex && \
     apk del shadow && \
     rm -rf /var/cache/apk/*
 
-# 配置系统语言环境
-RUN set -x && \
-    GLIBC_VERSION=2.30-r0 && \
-    wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub && \
-    wget -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk && \
-    wget -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}.apk && \
-    wget -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-i18n-${GLIBC_VERSION}.apk && \
-    if [ ! -f /etc/apk/keys/sgerrand.rsa.pub ]; then wget -q -O /etc/apk/keys/sgerrand.rsa.pub http://file.openeasy.cn/alpine/sgerrand.rsa.pub || exit 1; fi && \
-    if [ ! -f glibc-${GLIBC_VERSION}.apk ]; then wget -q http://file.openeasy.cn/alpine/glibc/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk || exit 1; fi && \
-    if [ ! -f glibc-bin-${GLIBC_VERSION}.apk ]; then wget -q http://file.openeasy.cn/alpine/glibc/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}.apk || exit 1; fi && \
-    if [ ! -f glibc-i18n-${GLIBC_VERSION}.apk ]; then wget -q http://file.openeasy.cn/alpine/glibc/${GLIBC_VERSION}/glibc-i18n-${GLIBC_VERSION}.apk || exit 1; fi && \
-    apk add glibc-bin-${GLIBC_VERSION}.apk glibc-i18n-${GLIBC_VERSION}.apk glibc-${GLIBC_VERSION}.apk && \
-    rm -rf glibc-bin-${GLIBC_VERSION}.apk glibc-i18n-${GLIBC_VERSION}.apk glibc-${GLIBC_VERSION}.apk && \
-    rm -rf /var/cache/apk/*
-RUN printf "zh_CN\nzh_HK\nzh_TW" | xargs -i /usr/glibc-compat/bin/localedef -c -f UTF-8 -i {} {}.UTF-8
-ENV LC_ALL=zh_CN.UTF-8
-ENV LANG=zh_CN.UTF-8
-
 # 安装依赖包
 RUN set -ex && \
     apk upgrade && \
@@ -61,6 +65,9 @@ RUN set -ex && \
     # # --with-python \
     # # --with-pam \
     # apk add krb5-libs libldap linux-pam python3 tcl perl
+
+
+ARG POSTGRES_VERSION=12.0
 
 ENV PGDATA="/var/lib/postgres"
 ENV POSTGRES_PASSWORD=""
